default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test: &test
  <<: *default
  database: db/test.sqlite3
  # host: localhost
  # adapter: postgresql
  # encoding: unicode
  # database: vrh
  # pool: 5
  # username: vrh
  # password: vrh

production:
  <<: *default
  # host: localhost
  # port: 5432
  # adapter: postgresql
  # encoding: unicode
  # database: vrh
  # pool: 5
  # username: vrh
  # password: vrh
